- name: start
  task: concurrently 'lerna run watch' 'nodemon --experimental-modules ./packages/example/src/server/index.mjs'

- name: format
  task: prettier --write 'packages/**/*.{js,json,yml}'

- name: postinstall
  task: lerna link

- name: build
  task: lerna run build

- name: lint
  task: eslint "packages/**/**.js"

- name: test
  tasks:
      - taskfile lint
