- name: start
  task: nodemon --experimental-modules ./example/server/index.mjs

- name: format
  tasks:
      - prettier --write '{bin,src,tests,example}/**/*.{mjs,js,css,html,yml,json}'
      - prettier --write '*.{mjs,js,css,html,yml,json}'

- name: build
  tasks:
      - mkdir -p es/production
      - mkdir -p es/development
      - - cp -r src/elements/ es/production/elements/
      - - cp -r src/elements/ es/development/elements/
      - - - node terser.config.js

- name: test/lint
  tasks:
      - readlint
      - - prettier --list-different '{bin,src,tests,example}/**/*.{mjs,js,css,html,yml,json}'
      - - prettier --list-different '*.{mjs,js,css,html,yml,json}'
      - - - eslint "{bin,src,tests,example}/**/**.js"
      - - - stylelint "example/**/**.css"
      - - - rm -rf es/
      - - - - NODE_ENV=production yarn build
      - - - - - find es/production/middleware/* -type d | xargs rm -rf
      - - - - - rm -rf es/production/elements
      - - - - - rm -rf es/production/core/debug/utils.js
      - - - - - - (cd es/production && tar -zcf ../../build.tar.gz .)
      - - - - - - - fslint --files=build.tar.gz --limit=3072 || rm -rf build.tar.gz es/
      - - - - - - - - rm -rf build.tar.gz es/

- name: test/spec
  task: NODE_ENV=test ava

- name: test/coverage
  tasks:
      - NODE_ENV=test nyc ava
      - - NODE_ENV=test nyc report --reporter=text-lcov | coveralls

- name: test/integration
  task: concurrently -k -s first 'yarn start' 'testcafe chrome:headless ./tests/integration/*.js'

- name: test
  tasks:
      - taskfile test/spec
      - - taskfile test/lint
      # - - - taskfile test/integration

- name: docker
  tasks:
      - docker build -t wildhoney/switzerland:latest .
      - - docker tag wildhoney/switzerland wildhoney/switzerland:$npm_package_version
      - - - docker push wildhoney/switzerland

- name: prepublish
  tasks:
      - rm -rf es
      - rollup -c bin/rollup.config.js
      - - mkdir -p es/production
      - - mkdir -p es/development
      - - - taskfile build

- name: postpublish
  tasks:
      - rm -rf es bin/index.js
      # - - taskfile docker
