- name: start
  task: nodemon --experimental-modules ./example/server/index.mjs

- name: format
  task: prettier --write 'src/**/*.js'

- name: lint
  task: eslint "src/**/*.js"

- name: test
  tasks:
      - taskfile lint
