- name: build
  task: BABEL_ENV=build webpack

- name: test
  tasks:
    - taskfile lint-js
    - taskfile lint-fs
    - - taskfile test-e2e
    # - taskfile spec

- name: lint
  tasks:
    - taskfile lint-js
    - taskfile lint-fs

- name: start
  task: (cd example/server && BABEL_ENV=server babel-node default.js)

- name: watch
  task: concurrently 'BABEL_ENV=build webpack --watch' 'npm run start'
  
- name: lint-fs
  tasks:
    - NODE_ENV=production npm run build
    - - gzip core.js -f
    - - - fslint --files=core.js.gz --limit=5120
    - - - - rm core.js.gz

- name: lint-js
  task: xo src/*.js

- name: test-e2e
  tasks:
    - BABEL_ENV=test-e2e webpack
    - - concurrently -k -s first 'npm run start' 'testcafe chrome:headless ./tests/integration/*.test.js'
    - - - BABEL_ENV=build webpack

- name: spec
  task: ava
