- name: start
  task: nodemon --experimental-modules ./example/server/index.mjs

- name: format
  tasks: 
    - prettier --write '{src,tests,example}/**/*.{js,css}'
    - prettier --write '*.{js,json}'

- name: build
  task: rollup -c rollup.config.js

- name: test/lint
  tasks:
      - eslint "{src,tests,example}/**/**.js"
      - stylelint "example/**/**.css"

- name: test/spec
  task: NODE_ENV=test nyc ava

- name: test/coverage
  task: NODE_ENV=test nyc report --reporter=text-lcov | coveralls

- name: test/integration
  task: concurrently -k -s first 'yarn start' 'testcafe chrome:headless ./tests/integration/*.js'

- name: test
  tasks:
      - taskfile test/lint
      - taskfile test/spec
      # - taskfile test/integration

- name: docker
  tasks:
    - docker build -t wildhoney/switzerland:latest .
    - - docker tag wildhoney/switzerland wildhoney/switzerland:$npm_package_version
    - - - docker push wildhoney/switzerland