- name: start
  task: nodemon --experimental-modules ./example/server/index.mjs

- name: format
  task: prettier --write '{src,test,example}/**/*.{js,css}'

- name: test/lint
  tasks:
    - eslint "{src,test,example}/**/**.js"
    - stylelint "example/**/**.css"

- name: test/spec
  task: ava

- name: test
  tasks:
      - taskfile test/lint
      - taskfile test/spec
