- name: start
  task: nodemon --experimental-modules ./example/server/index.mjs

- name: format
  tasks: 
    - prettier --write '{src,tests,example}/**/*.{js,css}'
    - prettier --write '*.{js,json}'

- name: build
  task: node terser.config.js

- name: test/lint
  tasks:
      - prettier --list-different '{src,tests,example}/**/*.{js,css}'
      - prettier --list-different '*.{js,json}'
      - - eslint "{src,tests,example}/**/**.js"
      - - stylelint "example/**/**.css"
      - - rm -rf es/ 
      - - - NODE_ENV=production yarn build
      - - - - (cd es/production && tar -zcf ../../build.tar.gz .)
      - - - - - fslint --files=build.tar.gz --limit=5500 || rm -rf build.tar.gz es/
      - - - - - - rm -rf build.tar.gz es/

- name: test/spec
  task: NODE_ENV=test nyc ava

- name: test/coverage
  task: NODE_ENV=test nyc report --reporter=text-lcov | coveralls

- name: test/integration
  task: concurrently -k -s first 'yarn start' 'testcafe chrome:headless ./tests/integration/*.js'

- name: test
  tasks:
      - taskfile test/lint
      - - taskfile test/spec
      # - - - taskfile test/integration

- name: docker
  tasks:
    - docker build -t wildhoney/switzerland:latest .
    - - docker tag wildhoney/switzerland wildhoney/switzerland:$npm_package_version
    - - - docker push wildhoney/switzerland

- name: prepublish
  tasks:
    - rm -rf es
    - - mkdir -p es/production
    - - mkdir -p es/development
    - - - taskfile build

- name: postpublish
  tasks:
    - rm -rf es
    - - taskfile docker
