- name: start
  task: nodemon --experimental-modules ./example/server/index.mjs

- name: format
  task: prettier --write '{src,test,example}/**/*.js'

- name: test/lint
  task: eslint "{src,test,example}/**/*.js"

- name: test/spec
  task: ava

- name: test
  tasks:
      - taskfile test/spec
      - taskfile test/lint
