- name: start
  task: nodemon --experimental-modules ./example/server/index.mjs

- name: format
  tasks:
      - prettier --write '{bin,src,tests,example}/**/*.{mjs,js,css,html,yml,json,md}'
      - prettier --write '*.{mjs,js,css,html,yml,json,md}'

- name: build
  tasks:
      - mkdir -p es/production
      - mkdir -p es/development
      - - cp -r src/elements/ es/production/elements/
      - - cp -r src/elements/ es/development/elements/
      - - - node terser.config.js

- name: test/lint
  tasks:
      - readlint
      - - prettier --list-different '{bin,src,tests,example}/**/*.{mjs,js,css,html,yml,json,md}'
      - - prettier --list-different '*.{mjs,js,css,html,yml,json,md}'
      - - - eslint "{bin,src,tests,example}/**/**.js"
      - - - stylelint "example/**/**.css"
      - - - rm -rf es/
      - - - - NODE_ENV=production yarn build
      - - - - - find es/production/middleware/* -type d | xargs rm -rf
      - - - - - rm -rf es/production/{elements,server}
      - - - - - - (cd es/production && tar -zcf ../../build.tar.gz .)
      - - - - - - - fslint --files=build.tar.gz --limit=3072 || rm -rf build.tar.gz es/
      - - - - - - - - rm -rf build.tar.gz es/

- name: test/spec
  task: ava

- name: test/coverage
  tasks:
      - mv ava.config.js ava.config.backup
      - - cp tests/helpers/ava.config.js ava.config.js
      - - - nyc --require esm --require node-url-imports --require core-js --require ./tests/helpers/browser-env.js ava || mv ava.config.backup ava.config.js 2>/dev/null
      - - - - NODE_ENV=test nyc report --reporter=text-lcov | coveralls || mv ava.config.backup ava.config.js 2>/dev/null
      - - - - - mv ava.config.backup ava.config.js 2>/dev/null

- name: test
  tasks:
      - taskfile test/lint
      - - taskfile test/spec

- name: prepublish
  tasks:
      - rm -rf es
      - rollup -c bin/rollup.config.js
      - - mkdir -p es/production
      - - mkdir -p es/development
      - - - taskfile build

- name: postpublish
  tasks:
      - rm -rf es bin/index.js
