- name: build
  task: BABEL_ENV=build webpack

- name: test
  tasks:
    - taskfile lint-js
    - taskfile lint-fs
    # - taskfile spec

- name: lint
  tasks:
    - taskfile lint-js
    - taskfile lint-fs

- name: start
  task: (cd example/server/ && BABEL_ENV=server babel-node default.js)

- name: watch
  task: BABEL_ENV=build webpack --watch
  
- name: lint-fs
  tasks:
    - NODE_ENV=production npm run build
    - - gzip core.js -f
    - - - fslint --files=core.js.gz --limit=3072
    - - - - rm core.js.gz

- name: lint-js
  task: xo src/*.js

- name: spec
  task: ava
