language: node_js
node_js: stable

script:
    - npm i
    - yarn
    - yarn test

after_success: yarn run coverage

deploy:
  provider: heroku
    skip_cleanup: true
  api_key:
    secure: JKPFWytHsrJAM4XgSibQbcadajk3S6yxHwnwkSeXsdNWCj5sfoxtd4oybWY1KTlSamCLKt5M0JejKl4YSOebFirISpjWRno605n6eo+A0gJS/AQZSl8Gc5RhPanAh98ec0S3qplN23rloIDqdQ7zge5v5vUxGkH8gyqxlfFnEjYKEo/sgsYAqHBtimp14BIu4n8FdKWsw3fK+FdZor6MMCgTs/ybJLXJ6LjAFGnWa9aal6LjaMa7F0dkH2u+Mezf3c4u0J969QRkJWL2dr2F0wdShCjYVys+YpZ81YXlRpFst9zGh4F4CII5lx2Zk/mj6NuO8olrS0IxuxU60UBPWORTIomh1MkdTwBajJX+qv1gnhIOstOPGO1yi7tLApwUU/JEaBUTRAuEgd3xFA9QL8giQW3tRwBsVr5lDOAOefn2kmp96r5g8A/9PrIssW1D3x4tHs+oq5/91S7xg17U7n0he4xYlSgERgg0+GRVaJHZqyqzVsP42MSDyD7/mqH/I6h1p+s1QSBXa3AgQaALY3cHq0jy7pt/b11NfnJou73vS35Fl+gdVzcIXO7fdk0t/810v6n9Va3a4jkCR1Vd5ZbSnUjqgiGmkwT4OAxbPjHmDUMskFZYM8/OT19vK9wweEVTKp0LHb+D1Un54bj+WPkhihcjVEucxalXDsiADvY=
  app: switzerland
  on:
    repo: Wildhoney/Switzerland
