language: node_js
node_js: stable

script:
    - npm i
    - yarn
    - yarn test

after_success: yarn run coverage
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: a8ttVC+E4aJxppu59j5Ietve76BuBRf5xQO1hPlDClWECqdBARjl9ncswCHXchqJVxNDFzUZZWBe2x2Onl5tHxKO7p1mR/rbpy70SdEysQrUHEaB/xl3NRxhVecZq8h5YFl6MBnn59NF99+kuN2PEJvSghfmuOVmIISz5kpBWcuV6w2eYg8slz4WXVycCn9aZ1eZW/Tl6r3I4Nzs+HxNKF6gm5Q6jNOMnV9B4nq47B06rg+OBccLqrlV8zwONZQEQiPy/c3/IlOeSu5g2juwUtY+kTi7j9QGaakF8e3hzhLhoJuvWyiHGIAT0lwApA62vQSueKqix7+8IwSn1WBm+VUhEBvceFjcpLBSvZFmekocPpdMWgtbl/XBc9pLpNCu8qjEmvlfBcVGl3Fkp3iFy5A1SmvMFknIA8LrWI1W6i/F0UcEchRa4O54JLwYrZYZsxRgxoAX0D3wTRo3EQ1VJ8oJpVjfwLaGn2JNKbIW4QQSScWRCblJqZ/fJhTk3SVFVczwMhWNmuPukdPoWjLaD+encfQwAgOgpLDi+zg6PceyybkE57C2cNq6mf/KWuE03zqM1q/tGn09v2rn12WXrbq04fG0Vl1tyU47PdGK9a+GSygmhY3QIm3ELmFuWbdDS9d8fMcfqyfBlDMwyF62ihSux1UY4Lk0Fe0LSruaCjw=
  app: switzerland
  on:
    repo: Wildhoney/Switzerland
